### ISSUE TITLE
 Error! Error fetching Vehicle Configuration from [http://datastore-proxy-redhat-iot.router.default.svc.cluster.local/api/vehicles/]. Reload to retry

### ISSUE THREAD

**Issue by kamranIoTDeveloper** [eclipselabs/eclipseiot-testbed-assettracking#1]

**Comment by kamranIoTDeveloper** [comment]
Receiving three errors on accessing dashboard.
Error! Error fetching Summaries Configuration from [http://datastore-proxy-eclipseiot-assettracking-testbed.35.187.55.21.nip.io/api/utils/summaries]. Reload to retry

Error! Error fetching Facilities from [http://datastore-proxy-eclipseiot-assettracking-testbed.35.187.55.21.nip.io/api/facilities]. Reload to retry

Error! Error fetching Vehicle Configuration from [http://datastore-proxy-eclipseiot-assettracking-testbed.35.187.55.21.nip.io/api/vehicles/]. Reload to retry

**Comment by kartben** [comment]
Thanks for reporting this. I would have fixed this earlier but I completely missed the GH notification :(
