### ISSUE TITLE
Online Demo not working Properly http://dashboard-eclipseiot-assettracking-testbed.35.187.55.21.nip.io

### ISSUE THREAD

**Issue by kamranIoTDeveloper** [eclipselabs/eclipseiot-testbed-assettracking#2]

**Comment by mpschuetze** [comment]
Hi Ben. I'd like to demo the working Asset Tracker. Will the hosted demo get righted soon? Just curious. Thanks.

**Comment by kartben** [comment]
Hey guys. Thanks for reporting this, and sorry for the delay. This is now fixed!
