### ISSUE TITLE
I am accessing dashboard by http://dashboard-redhat-iot.apps.127.0.0.1.nip.io(From system in which test bed/openshift server is installed ), How to access it in Local area (From other PC))

### ISSUE THREAD

**Issue by kamranIoTDeveloper** [eclipselabs/eclipseiot-testbed-assettracking#3]

**Comment by kamranIoTDeveloper** [comment]
Problem solved by replacing subdomain with http://dashboard-redhat-iot.apps.192.168.10.5.nip.io.

but services which are running on http/https are accessible, and services like MQTT broker on port 1883 is not accessible through its hostname outside of cluster. i-e http://broker-redhat-iot.apps.192.168.10.5.nip.io/

**Comment by kartben** [comment]
The mqtt broker is *never* accessible from outside the cluster over the regular TCP/1883 port. You have to connect to it over websockets, which is routed over HTTP out of the cluster. The URL would be something like ws://broker-eclipseiot-assettracking-testbed.192.168.10.5.nip.io/mqtt

**Comment by kamranIoTDeveloper** [comment]
@kartben  thanks, can u send me some link to resolve the issue.

**Comment by kartben** [comment]
Not sure what you mean?

**Comment by kamranIoTDeveloper** [comment]
@kartben I mean "How to connect to MQTT broker over websockets which is routed over HTTP out of the cluster"

**Comment by kamranIoTDeveloper** [comment]
@kartben thanks problem solved
